#!/bin/bash

# This script runs on the HOST machine to ensure the required .env file exists.
# It creates a template .env file if one is not already present, with comments
# describing the necessary configuration for different operating systems (Linux, Windows, macOS).

# Get the directory where this script is located
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Define the path for the .env file, which should be one level up from this script (in the same directory as docker-compose.yml)
ENV_FILE="${SCRIPT_DIR}/../.env"

# --- Check if the .env file already exists ---
if [ -f "${ENV_FILE}" ]; then
    echo "The environment configuration file (${ENV_FILE}) already exists. Skipping creation."
    echo "Please edit it manually if you need to change the settings."
    exit 0
fi

# --- Create the new .env file with configuration comments ---
echo "Creating a template environment configuration file: ${ENV_FILE}"

cat > "${ENV_FILE}" <<EOL
# ----------------------------------------------------------------------
# Dev container environment configuration
# This file is auto-generated by initialize.sh because it did not exist.
# Please uncomment and adjust the settings below based on your host OS.
# ----------------------------------------------------------------------

# --- Configuration for X11 forwarding (e.g., to display graphical applications) ---

# 🐧 LINUX NATIVE DOCKER CONFIGURATION:
# Uncomment these lines if you are running on a native Linux host.
# DISPLAY_CONFIG=\${DISPLAY}
# NETWORK_MODE_CONFIG=host

# 🍎 WINDOWS / 🍏 MACOS DOCKER DESKTOP CONFIGURATION:
# Uncomment these lines if you are running on Windows or macOS using Docker Desktop.
# Docker Desktop requires 'host.docker.internal' to reference the host machine.
DISPLAY_CONFIG=host.docker.internal:0
NETWORK_MODE_CONFIG=bridge

# 📝 NOTE: If using Linux and you still want a bridge network,
# you may need to install an X server (like VcXsrv on Windows or XQuartz on macOS)
# and replace 'host.docker.internal' with your host machine's specific IP address.

# ----------------------------------------------------------------------

# --- Default Fallback (Safe to keep commented unless you know your setup) ---
# DISPLAY_CONFIG=
# NETWORK_MODE_CONFIG=bridge
EOL

echo "Template file created. **ACTION REQUIRED:**"
echo "Please open ${ENV_FILE} and uncomment the configuration block that matches your host OS (Linux or Windows/macOS)."