#!/bin/bash

# This script runs on the HOST machine before the container is created.
# It detects the host OS and creates a .env file for Docker Compose.

# Get the directory where this script is located
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# CORRECTED ENV FILE PATH: Create the .env file in the same directory as the docker-compose.yml file.
# From this script's location (scripts/), that is one level up (../).
ENV_FILE="${SCRIPT_DIR}/../.env"

# Default to Docker Desktop (Windows/macOS) settings
DISPLAY_CONFIG="host.docker.internal:0"
NETWORK_MODE_CONFIG="bridge" # Standard bridge network

# Check if we are on Linux
if [[ "$(uname)" == "Linux" ]]; then
    echo "Linux host detected. Configuring for native Docker."
    # Use the host's display
    DISPLAY_CONFIG="${DISPLAY}"
    # Use the host's network for easy X11 forwarding
    NETWORK_MODE_CONFIG="host"
else
    echo "Windows/macOS host detected. Configuring for Docker Desktop."
fi

# Write the configuration to the .env file
# Docker Compose will automatically read this file because it's in the same directory.
cat > "${ENV_FILE}" <<EOL
# This file is auto-generated by initialize.sh
DISPLAY_CONFIG=${DISPLAY_CONFIG}
NETWORK_MODE_CONFIG=${NETWORK_MODE_CONFIG}
EOL

echo "Dev container environment configured in ${ENV_FILE}"
