# This workflow builds an Arduino Nano sketch using a single-job strategy.
# It leverages caching for dependencies to speed up subsequent runs.
name: Build Arduino Nano Sketch (Single Job)
run-name: Build Arduino Nano Sketch for ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - build/all
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Optional build name or version'
        required: false
        default: 'dev-build'

jobs:
  # ===============================================================
  # JOB: SETUP, COMPILE, AND UPLOAD
  # ===============================================================
  build:
    runs-on: linux_amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          token: ${{ secrets.GH_PAT }}

      # --- Cache and Install Arduino AVR Core ---
      - name: Cache Arduino AVR core
        id: cache-avr-core
        uses: actions/cache@v3
        with:
          path: ~/.arduino15/packages/arduino
          key: avr-core-${{ runner.os }}

      - name: Install Arduino AVR Core
        # This step runs only if the cache was not found
        if: steps.cache-avr-core.outputs.cache-hit != 'true'
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      # --- Cache and Install Libraries ---
      - name: Cache Arduino libraries
        id: cache-arduino-libs
        uses: actions/cache@v3
        with:
          path: ~/Arduino/libraries
          # The cache key includes a hash of the dependencies file.
          # The cache will be invalidated and libs re-installed only when this file changes.
          key: nano-libs-${{ runner.os }}-${{ hashFiles('workflow_test/arduino/library-dependencies.txt') }}

      - name: Install libraries
        # This step runs only if the cache was not found
        if: steps.cache-arduino-libs.outputs.cache-hit != 'true'
        run: |
          while IFS= read -r lib || [[ -n "$lib" ]]; do
            # Skip empty lines and comments
            if [ -z "$lib" ] || [[ "$lib" =~ ^#.* ]]; then continue; fi
            # Install from Git URL or from Arduino Library Manager
            if [[ "$lib" =~ ^(https?|git)://.*\.git$ ]]; then
              arduino-cli lib install --git-url "$lib"
            else
              arduino-cli lib install "$lib"
            fi
          done < workflow_test/arduino/library-dependencies.txt

      # --- Compile the Sketch ---
      - name: Compile sketch
        run: |
          mkdir -p build/nano
          arduino-cli compile \
            --fqbn arduino:avr:nano \
            workflow_test/arduino/arduino.ino \
            --output-dir build/nano \
            --verbose

      # --- Upload Final Binary ---
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nano-binary-${{ inputs.build_name || github.run_number }}
          path: build/nano